/**
 * Database package entry point
 *
 * Re-exports Prisma Client and types for use by API and other services
 *
 * In development, this uses the generated TypeScript client directly.
 * In production Docker, the generated client is in node_modules/.prisma/client
 */

// Import from the generated client location for TypeScript
// @ts-expect-error - this path is generated by Prisma and may not exist until after generation
export { PrismaClient, Prisma } from '../../node_modules/.prisma/client';
